### ISSUE TITLE
Testing the V2

### ISSUE THREAD

**Issue by bactisme** [fubralimited/php-oara#48]
Hi,

I am preparing a small script for my needs, I saw a V2 branch and I naturally wanted to use it, if it's the next version.

I see active development, so I suppose you are well aware of this problems. Let me still, express the errors I noted: 

1. Ebay (better to use format instead)
`Fatal error: Call to undefined method DateTime::toSTring() in (...)/vendor/fubralimited/php-oara/Oara/Network/Publisher/Ebay.php on line 125
`

2. Zanox
`Fatal error: Call to a member function setConnectId() on a non-object in (...)/vendor/fubralimited/php-oara/Oara/Network/Publisher/Zanox/Zapi/includes/ApiMethods.php on line 287`

3. Amazon FR doesn't work (Empty array and getTransactionsList, checkConnection ask a page that give a http 500).

4. TradeDoubler (object is actually type \DateTime)
```
Fatal error: Uncaught exception 'Exception' with message '
 Date Format not supported
' in (...)/vendor/fubralimited/php-oara/Oara/Network/Publisher/TradeDoubler.php:512
Stack trace:
#0 (...)/vendor/fubralimited/php-oara/Oara/Network/Publisher/TradeDoubler.php(410): Oara\Network\Publisher\TradeDoubler->formatDate(Object(DateTime))
```

Also, do you have any roadmap? How can I help?

**Comment by cmorillo** [comment]
Hi,
We are currently testing/fixing all the networks, our plan is to have them all in around 10 days

    Ebay (better to use format instead)
    Yep we have to change it to be format

    Zanox
    It looks like a problem on the Zanox API , probably need to update it to the last version

    Amazon FR doesn't work (Empty array and getTransactionsList, checkConnection ask a page that give a http 500).

Amazon changed they way to log in , probably you will need to request access to a new feed to you amazon manager, we are trying  to get that solved

    TradeDoubler (object is actually type \DateTime)
We have change the whole system to use DateTime instead of Zend_Date so we may have still some problems but they will be fixed

If you are able to manage to fix any of them please do a pull request and then we will merge it.
